name: Generate Snake Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3 to use Node 16

    - name: Generate snake game
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}

    - name: Upload generated content
      run: |
        mv dist/github-snake.svg ./github-snake.svg
        mv dist/github-snake-dark.svg ./github-snake-dark.svg
        mv dist/ocean.gif ./ocean.gif
